using System;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace PrefabAlerts {
internal static class OverrideAlertSettings
{
    private const string KeyPrefix     = "PrefabAlerts.OverrideColors.";
    private const char   ListSeparator = '\n';

    private static readonly Color DefaultHeaderBackground      = new(1f, 1f, 0f, 0.70f);
    private static readonly Color DefaultHeaderText            = Color.black;
    private static readonly Color DefaultHierarchyText         = new(1f, 1f, 0f, 0.75f);
    private static readonly Color DefaultHighlighterText       = new(1f, 1f, 0f, 0.75f);

    // NOTE:
    // Overrides consisting ONLY of these property paths are ignored
    // because they are regenerated by the engine/packages every validation
    // and can never be resolved by Apply/Revert.
    // EX: 'Netcode for GameObjects' rewrites GlobalObjectIdHash in OnValidate,
    // so nested NetworkObject prefabs always report this override.
    private static readonly string[] DefaultIgnoredPropertyPaths =
    {
        "GlobalObjectIdHash"
    };

    private static HashSet<string> _ignoredPropertyPathsCache;

    internal static event Action Changed;

    internal static Color HeaderBackground
    {
        get => Load("HeaderBackground", DefaultHeaderBackground);
        set => Save("HeaderBackground", value);
    }

    internal static Color HeaderText
    {
        get => Load("HeaderText", DefaultHeaderText);
        set => Save("HeaderText", value);
    }

    internal static Color HierarchyText
    {
        get => Load("HierarchyText", DefaultHierarchyText);
        set => Save("HierarchyText", value);
    }

    internal static Color HighlighterText
    {
        get => Load("HighlighterText", DefaultHighlighterText);
        set => Save("HighlighterText", value);
    }

    internal static string[] IgnoredPropertyPaths
    {
        get => LoadList("IgnoredPropertyPaths", DefaultIgnoredPropertyPaths);
        set
        {
            SaveList("IgnoredPropertyPaths", value);
            _ignoredPropertyPathsCache = null;
        }
    }

    internal static bool IsIgnoredProperty(string propertyPath)
    {
        _ignoredPropertyPathsCache ??= new HashSet<string>(IgnoredPropertyPaths);

        return _ignoredPropertyPathsCache.Contains(propertyPath);
    }

    internal static void ResetToDefaults()
    {
        HeaderBackground     = DefaultHeaderBackground;
        HeaderText           = DefaultHeaderText;
        HierarchyText        = DefaultHierarchyText;
        HighlighterText      = DefaultHighlighterText;
        IgnoredPropertyPaths = (string[])DefaultIgnoredPropertyPaths.Clone();
    }

    internal static void RaiseChanged()
    {
        Changed?.Invoke();

        EditorApplication.RepaintHierarchyWindow();

        foreach (var inspector in Resources.FindObjectsOfTypeAll<EditorWindow>())
        {
            if (inspector != null && inspector.GetType().Name == "InspectorWindow")
            {
                inspector.Repaint();
            }
        }
    }

    private static Color Load(string name, Color fallback)
    {
        var stored = EditorPrefs.GetString(KeyPrefix + name, string.Empty);

        return ColorUtility.TryParseHtmlString("#" + stored, out var color) ? color : fallback;
    }

    private static void Save(string name, Color value)
    {
        EditorPrefs.SetString(KeyPrefix + name, ColorUtility.ToHtmlStringRGBA(value));
    }

    private static string[] LoadList(string name, string[] fallback)
    {
        // NOTE:
        // A missing key returns the default list, while an explicitly emptied
        // list (stored as "") returns an empty array. This lets the user clear
        // the list on purpose.
        if (!EditorPrefs.HasKey(KeyPrefix + name))
        {
            return (string[])fallback.Clone();
        }

        return EditorPrefs.GetString(KeyPrefix + name, string.Empty)
                          .Split(ListSeparator)
                          .Select(entry => entry.Trim())
                          .Where (entry => entry.Length > 0)
                          .ToArray();
    }

    private static void SaveList(string name, string[] value)
    {
        var cleaned = (value ?? Array.Empty<string>())
                      .Select(entry => entry?.Trim())
                      .Where (entry => !string.IsNullOrEmpty(entry));

        EditorPrefs.SetString(KeyPrefix + name, string.Join(ListSeparator.ToString(), cleaned));
    }
}}